import { chromium } from '@playwright/test';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 420, height: 820 } });
const err=[];
p.on('pageerror', e=>err.push(e.message));
p.on('console', m => { const t=m.text(); if(t.includes('[m]')) console.log(t); });
await p.goto('http://localhost:5200/', { waitUntil: 'domcontentloaded' });
await p.waitForTimeout(1500);
const dev = await p.getByText('Dev-Login',{exact:false}).count();
console.log('[m] devbtn='+dev);
if (dev) { await p.getByText('Dev-Login',{exact:false}).first().click().catch(()=>{}); await p.waitForTimeout(2500); await p.goto('http://localhost:5200/',{waitUntil:'domcontentloaded'}); await p.waitForTimeout(1500); }
const cards = await p.locator('.recipecard').count();
const navExists = await p.locator('.nav a[href="/verlauf"]').count();
console.log('[m] cards='+cards+' navVerlauf='+navExists+' navAPI='+await p.evaluate(()=>!!window.navigation));
await p.evaluate(() => {
  const o=document.startViewTransition.bind(document);
  document.startViewTransition=(cb)=>{ const vt=o(cb);
    vt.ready.then(()=>{ const motif=document.getAnimations().find(x=>x.effect&&x.effect.pseudoElement==='::view-transition-group(zk-shared-motif)');
      console.log('[m] '+window.__phase+' motif='+(!!motif));
      if(motif) motif.finished.then(()=>console.log('[m] '+window.__phase+' COMPLETED')).catch(()=>console.log('[m] '+window.__phase+' CANCELLED')); }); return vt; };
});
if (navExists) await p.locator('.nav a[href="/verlauf"]').click(); else await p.goto('http://localhost:5200/verlauf',{waitUntil:'domcontentloaded'});
await p.waitForTimeout(1200);
await p.evaluate(()=>window.__phase='FWD');
await p.locator('.recipecard').nth(1).click();
await p.waitForFunction(()=>location.pathname.startsWith('/rezept/'),{timeout:5000}).catch(()=>{});
await p.waitForTimeout(900);
await p.evaluate(()=>window.__phase='BROWSER-BACK');
await p.goBack();
await p.waitForTimeout(900);
await p.evaluate(()=>window.__phase='FWD2');
await p.locator('.recipecard').nth(1).click();
await p.waitForFunction(()=>location.pathname.startsWith('/rezept/'),{timeout:5000}).catch(()=>{});
await p.waitForTimeout(700);
await p.evaluate(()=>window.__phase='BUTTON');
await p.getByText('Zurück',{exact:false}).first().click();
await p.waitForTimeout(900);
console.log('[m] errors='+JSON.stringify(err.slice(0,3)));
await b.close(); process.exit(0);
