"""feedback + user preferences

Revision ID: 38a858dbaaf4
Revises: 7f8cfbb340c5
Create Date: 2026-07-11 03:17:29.007548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38a858dbaaf4'
down_revision: Union[str, Sequence[str], None] = '7f8cfbb340c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('feedback_grund', sa.String(length=255), nullable=False, server_default=''))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferences_json', sa.Text(), nullable=False, server_default='{}'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('preferences_json')

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('feedback_grund')
        batch_op.drop_column('feedback')

    # ### end Alembic commands ###
