"""recipe notes + cooked count

Revision ID: 40be5d258d4d
Revises: 38a858dbaaf4
Create Date: 2026-07-11 03:30:29.860498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40be5d258d4d'
down_revision: Union[str, Sequence[str], None] = '38a858dbaaf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notiz', sa.Text(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('gekocht_count', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('gekocht_count')
        batch_op.drop_column('notiz')

    # ### end Alembic commands ###
