"""recipe share_token

Revision ID: b735f1e55d6c
Revises: d1c7bea3877b
Create Date: 2026-07-10 22:50:57.420053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b735f1e55d6c'
down_revision: Union[str, Sequence[str], None] = 'd1c7bea3877b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_token', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_recipes_share_token'), ['share_token'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipes_share_token'))
        batch_op.drop_column('share_token')

    # ### end Alembic commands ###
