"""initial schema

Revision ID: d1c7bea3877b
Revises: 
Create Date: 2026-07-10 07:16:03.056941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1c7bea3877b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('allowlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allowlist_email'), ['email'], unique=True)

    op.create_table('generation_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('params_hash', sa.String(length=64), nullable=False),
    sa.Column('recipe_json', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generation_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_cache_params_hash'), ['params_hash'], unique=True)

    op.create_table('rate_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'day', name='uq_ratelimit_scope_day')
    )
    with op.batch_alter_table('rate_limits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rate_limits_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_rate_limits_scope'), ['scope'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_sub', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('picture_url', sa.String(length=1024), nullable=False),
    sa.Column('adult_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_google_sub'), ['google_sub'], unique=True)

    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('params_json', sa.Text(), nullable=False),
    sa.Column('recipe_json', sa.Text(), nullable=False),
    sa.Column('titel', sa.String(length=255), nullable=False),
    sa.Column('kueche', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipes_kueche'), ['kueche'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipes_titel'), ['titel'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipes_user_id'), ['user_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'recipe_id', name='uq_favorite_user_recipe')
    )
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorites_recipe_id'), ['recipe_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favorites_user_id'), ['user_id'], unique=False)

    op.create_table('shopping_list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('menge', sa.Float(), nullable=True),
    sa.Column('einheit', sa.String(length=32), nullable=False),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shopping_list_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shopping_list_items_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_list_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shopping_list_items_user_id'))

    op.drop_table('shopping_list_items')
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorites_user_id'))
        batch_op.drop_index(batch_op.f('ix_favorites_recipe_id'))

    op.drop_table('favorites')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_token'))

    op.drop_table('sessions')
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipes_user_id'))
        batch_op.drop_index(batch_op.f('ix_recipes_titel'))
        batch_op.drop_index(batch_op.f('ix_recipes_kueche'))
        batch_op.drop_index(batch_op.f('ix_recipes_created_at'))

    op.drop_table('recipes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_google_sub'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('rate_limits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rate_limits_scope'))
        batch_op.drop_index(batch_op.f('ix_rate_limits_day'))

    op.drop_table('rate_limits')
    with op.batch_alter_table('generation_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generation_cache_params_hash'))

    op.drop_table('generation_cache')
    with op.batch_alter_table('allowlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allowlist_email'))

    op.drop_table('allowlist')
    # ### end Alembic commands ###
